function result = runScreeningPipeline(imgPath, cfgPath)
%RUNSCREENINGPIPELINE End-to-end DR screening: QA -> enhance -> segment ->
%   grade -> explain -> report. This is the single entry point the FastAPI
%   gateway calls via MATLAB Engine API for Python (see
%   python/gateway/matlab_bridge.py).
%
%   result = runScreeningPipeline('data/aptos2019/sample_001.png')
%   result = runScreeningPipeline(imgPath, 'config/pipeline_config.yaml')
%
%   Output struct mirrors docs/api_contract.md's /api/screen response shape
%   (minus HTTP-specific fields, which the gateway adds).

    if nargin < 2
        cfgPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', ...
            'config', 'pipeline_config.yaml');
    end
    cfg = loadConfig(cfgPath);

    t0 = tic;
    img = ioHelpers('readImage', imgPath);

    % --- Stage 1: Quality gate -----------------------------------------------
    quality = assessImageQuality(img, cfg);
    if ~quality.adequate
        result = struct( ...
            'status', 'rejected', ...
            'quality', quality, ...
            'recapture_message', quality.recapture_message, ...
            'processing_time_ms', round(toc(t0) * 1000) ...
        );
        return
    end

    borderline = (quality.sharpness_score < 0.7) || (quality.illumination_score < 0.7);
    if borderline
        workingImg = enhanceImage(img, cfg);
    else
        workingImg = img;
    end

    % --- Stage 2: Structure & lesion segmentation ----------------------------
    discFovea = segmentOpticDiscFovea(workingImg);
    vesselMask = segmentVessels(workingImg, cfg);
    maResult = detectMicroaneurysms(workingImg, vesselMask, cfg);
    exudateResult = segmentExudates(workingImg, discFovea.disc_mask);
    hemResult = classifyHemorrhages(workingImg, vesselMask, discFovea.disc_mask);
    nvResult = detectNeovascularization(vesselMask, discFovea);

    lesionFeatures = struct( ...
        'microaneurysm_count', maResult.count, ...
        'microaneurysm_centroids', maResult.centroids, ...
        'hemorrhage', hemResult, ...
        'hard_exudate_mask', exudateResult.hard_exudate_mask, ...
        'hard_exudate_area_pct', exudateResult.hard_exudate_area_pct, ...
        'soft_exudate_present', exudateResult.soft_exudate_present, ...
        'nv', nvResult, ...
        'vessel_mask', vesselMask, ...
        'enhanced_image', workingImg ...
    );

    % --- Stage 3: Severity grading --------------------------------------------
    grading = gradeDRSeverity(lesionFeatures, cfg);
    calibration = calibrateConfidence(grading.model_confidence, cfg);
    grading.model_confidence = calibration.confidence;
    grading.requires_human_review = calibration.requires_human_review;

    % --- Stage 4: Explainability ------------------------------------------------
    net = getSeverityNet(cfg); % returns [] if no trained model on disk yet
    ensembleWeights = [];
    if isfield(cfg.paths, 'severity_model_weights')
        ensembleWeights = cfg.paths.severity_model_weights;
    end
    camOverlay = generateGradCAM(workingImg, net, grading.icdr_level, cfg, ensembleWeights);
    if isequal(camOverlay, workingImg)
        % No trained net yet -> fall back to a lesion-evidence overlay so the
        % explainability output is still meaningful during development.
        camOverlay = buildLesionEvidenceOverlay(workingImg, lesionFeatures);
    end

    report = generateReport(imgPath, quality, grading, lesionFeatures, camOverlay, cfg);

    % --- Assemble final result ------------------------------------------------
    ruleLabels = {'No DR', 'Mild NPDR', 'Moderate NPDR', 'Severe NPDR', 'Proliferative DR'};
    result = struct( ...
        'status', 'graded', ...
        'quality', quality, ...
        'grading', struct( ...
            'icdr_level', grading.icdr_level, ...
            'icdr_label', grading.icdr_label, ...
            'referable', grading.referable, ...
            'confidence', grading.model_confidence, ...
            'requires_human_review', grading.requires_human_review ...
        ), ...
        'grading_paths', struct( ...
            'rule_based_level', grading.rule_based_level, ...
            'rule_based_label', ruleLabels{grading.rule_based_level + 1}, ...
            'learned_level', grading.icdr_level, ...
            'learned_label', grading.icdr_label, ...
            'disagreement', grading.rule_based_level ~= grading.icdr_level ...
        ), ...
        'lesions', struct( ...
            'microaneurysm_count', maResult.count, ...
            'hemorrhage_count', hemResult.count, ...
            'hard_exudate_area_pct', exudateResult.hard_exudate_area_pct, ...
            'soft_exudate_present', exudateResult.soft_exudate_present, ...
            'neovascularization_detected', nvResult.nvd_suspected || nvResult.nve_suspected ...
        ), ...
        'report', report, ...
        'processing_time_ms', round(toc(t0) * 1000) ...
    );
end

function overlay = buildLesionEvidenceOverlay(img, lesionFeatures)
    overlay = img;
    if any(lesionFeatures.hard_exudate_mask(:))
        overlay = imoverlay(overlay, lesionFeatures.hard_exudate_mask, 'cyan');
    end
    if any(lesionFeatures.hemorrhage.mask(:))
        overlay = imoverlay(overlay, lesionFeatures.hemorrhage.mask, 'red');
    end
end
